server:
  port: 9191

spring:
  cloud: 
    gateway:
     routes:
      - id: PLAN-PRODUCTION-SERVICE
        uri: lb://PLAN-PRODUCTION-SERVICE
        predicates: 
         - Path=/plan-production/**
      - id: WATER-CONSUMPTION-SREVICE
        uri: lb://WATER-CONSUMPTION-SERVICE
        predicates:
         - Path=/water-consumption/**
