server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:h2:mem:plan-production
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: create
  h2:
    console.enabled: true