server:
  port: 9002
  servlet:
   context-path: /plan-production
  
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:plan-production
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  zipkin:
    base-url: http://localhost:9411/

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"