server:
  port: 9002
  servlet:
   context-path: /plan-production
  
spring:
  datasource:
    url: jdbc:h2:mem:plan-production
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"